/**
 * Canonical clause type labels derived from the CUAD dataset + common contract categories.
 * These are the ONLY valid values for obligation_type / detected_type.
 * Using a fixed, well-known set ensures consistent sorting and filtering across all documents.
 */
export const CANONICAL_CLAUSE_TYPES = [
  'Acceleration Clause',
  'Acceleration of Rent Clause',
  'Acceptance Criteria',
  'Access Clause',
  'Acknowledgment Clause',
  'Accord and Satisfaction',
  'Accrued Rights',
  'Additional Insured',
  'Affiliate License',
  'Agreement Date',
  'Agreement Not to Sue',
  'AI Use Consent Clause',
  'Amended & Restated Agreement',
  'Amendment',
  'Amendment of Bylaws Clause',
  'Anti-Assignment',
  'Anti-Corruption / FCPA Clause',
  'Anti-Dilution Clause',
  'Arbitration',
  'Assignment Clause',
  'At-Will Employment',
  'Attorneys Fees Clause',
  'Audit Clause',
  'Audit Rights',
  'Background Check Requirement',
  'Benchmarking Clause',
  'Best Efforts / Reasonable Efforts',
  'Boilerplate',
  'Break Clause',
  'Breach of Contract',
  'Call / Put Option Clause',
  'Change Of Control',
  'Clawback Clause',
  'Competitive Restriction Exception',
  'Compliance with Laws',
  'Conditions of Contract',
  'Conditions Precedent',
  'Confidentiality',
  'Consideration Clause',
  'Consequential Damages Waiver',
  'Counterparts Clause',
  'Counteroffer',
  'Covenant Not to Compete (M&A)',
  'Covenant Not To Sue',
  'Covenant of Quiet Enjoyment',
  'Cross-Default Clause',
  'Data Protection Clause',
  'Disclaimer',
  'Dispute Resolution',
  'Document Name',
  'Drag-Along Rights',
  'Duty to Mitigate',
  'Early Termination',
  'Earn-Out Clause',
  'Easement Agreement Clause',
  'Effective Date',
  'Entire Agreement',
  'Escalation Clause',
  'Escrow',
  'Estoppel Letters Clause',
  'Evergreen Clause',
  'Exclusive Supplier Clause',
  'Exclusivity',
  'Exculpatory Clause',
  'Expiration Date',
  'Force Majeure',
  'Frustration of Purpose',
  'Good Faith & Fair Dealing',
  'Governing Law',
  'Gross-Up Clause',
  'Guarantee Clause',
  'Hardship Clause',
  'Hold Harmless',
  'Holdback Clause',
  'Indemnification',
  'Independent Contractor',
  'Insurance',
  'Intellectual Property Clause',
  'IP Ownership Assignment',
  'Irrevocable Or Perpetual License',
  'Joint & Several Liability',
  'Joint IP Ownership',
  'Jurisdiction / Choice of Law',
  'Key Person Clause',
  'Letter of Intent (LOI)',
  'License Grant',
  'Limited Liability',
  'Liquidated Damages',
  'Liquidation Preference',
  'Lock-Up Agreement',
  'Material Adverse Change (MAC/MAE)',
  'Material Breach',
  'Milestone Clause',
  'Minimum Commitment',
  'Most Favored Nation',
  'Negative Pledge',
  'No-Shop Clause',
  'No-Solicit Of Customers',
  'No-Solicit Of Employees',
  'Non-Circumvention Clause',
  'Non-Compete',
  'Non-Disparagement',
  'Non-Solicitation',
  'Non-Transferable License',
  'Non-Waiver Clause',
  'Notice and Cure',
  'Notice Clause',
  'Notice Period To Terminate Renewal',
  'Notice Requirements',
  'Novation',
  'Pari Passu Clause',
  'Parol Evidence Rule',
  'Parties',
  'Payment Terms',
  'Penalty Clause',
  'Post-Termination Services',
  'Power of Attorney',
  'Price Adjustment / Escalation',
  'Price Restrictions',
  'Promissory Estoppel',
  'Publicity / Press Release Clause',
  'Quantum Meruit',
  'Recording Consent Clause',
  'Release of Claims',
  'Renewal Clause',
  'Renewal Term',
  'Representations And Warranties',
  'Representations vs. Warranties',
  'Retention of Title',
  'Revenue/Profit Sharing',
  'Right of First Offer (ROFO)',
  'Right of First Refusal (ROFR)',
  'ROFR/ROFO/ROFN',
  'Sanctions & Export Control',
  'Scope of Work',
  'Set-Off / Offset Clause',
  'Severability',
  'Side Letter',
  'SLA Clause',
  'Source Code Escrow',
  'Specific Performance',
  'Standstill Clause',
  'Statute of Frauds',
  'Step-In Rights',
  'Subrogation',
  'Subordination Clause',
  'Successors and Assigns',
  'Sunset Clause',
  'Survival Clause',
  'Tag-Along Rights (Co-Sale)',
  'Tail Period / Tail Clause',
  'Taxes',
  'Term',
  'Termination by Either Party',
  'Termination Fee / Break-Up Fee',
  'Termination For Convenience',
  'Termination of Lease',
  'Termination Payment',
  'Termination With Cause',
  'Termination Without Cause',
  'Third Party Beneficiary',
  'Time is of the Essence',
  'Unlimited License',
  'Unlimited/All-You-Can-Eat License',
  'Unjust Enrichment',
  'Volume Restriction',
  'Waiver',
  'Waiver of Subrogation',
  'Warranties',
  'Warranty Disclaimer / As Is',
  'Warranty Duration',
  'Work for Hire / IP Ownership',
  'Other',
] as const;

export type CanonicalClauseType = typeof CANONICAL_CLAUSE_TYPES[number];

/**
 * Per-type keyword signatures derived from the CUAD dataset via TF-IDF.
 * These are the most discriminative tokens for each canonical clause type —
 * words that appear frequently in that type but rarely in others.
 * Used as a rate-limit / offline fallback when Groq is unavailable.
 */
export const CLAUSE_TYPE_SIGNATURES: Record<string, string[]> = {
  'Affiliate License':             ['sublicense','sublicenses','sublicensee','spinco','remainco','subsidiary','perpetual','irrevocable','royalty','worldwide','grants','patents','intellectual','field','core','library','shared','import','grant'],
  'AI Use Consent Clause':         ['artificial','intelligence','automated','algorithm','algorithmic','biometric','profiling','decision-making','consent','riders','passengers','passenger','processing','model','models','analytics','opt'],
  'Anti-Assignment':               ['assign','assigned','assignment','assignable','assigning','delegate','transfer','consent','void','null','neither','withheld','unreasonably','purported','assets','successor','reorganization','merger'],
  'Audit Rights':                  ['audit','auditing','audited','auditor','auditors','audits','books','records','inspect','inspection','examine','examination','verify','hours','normal','certified','review','accuracy','conducted'],
  'Background Check Requirement':  ['background','check','checks','screening','screen','criminal','history','fingerprint','fingerprinting','mvr','driving','record','driver','drivers','rescreen','recurring','renewal','annually','biennial'],
  'Change Of Control':             ['change','control','merger','consolidation','voting','acquisition','acquirer','stock','securities','reorganization','transaction','terminate','consent','successor','ownership'],
  'Competitive Restriction Exception': ['exclusivity','competitive','competing','category','exception','carve','merchants','arrangements','prevent','listed'],
  // 'information', 'disclosure', 'trade' removed — too generic, cause over-labeling
  // in clauses that merely reference confidential information in passing
  'Confidentiality':               ['confidential','nondisclosure','confidentially','proprietary','secrets','disclosed','disclose'],
  'Consequential Damages Waiver':  ['consequential','special','incidental','punitive','exemplary','indirect','damages','liable','negligence','tort','lost','profits','loss','possibility','advised','theory','arising'],
  'Covenant Not To Sue':           ['contest','validity','challenge','enforceability','trademarks','marks','trademark','register','impair','contesting','attack','ownership','registration'],
  'Dispute Resolution':            ['arbitration','arbitrator','mediation','mediator','arbitrate','jams','dispute','proceedings','administered','rules'],
  'Effective Date':                ['effective','commencement','commencing','commences'],
  'Exclusivity':                   ['exclusive','exclusively','exclusivity','appoints','territory','distribute','sell','worldwide','remarketing'],
  'Expiration Date':               ['expiration','expires','expiry'],
  'Force Majeure':                 ['force','majeure','acts','flood','earthquake','pandemic','epidemic','governmental','strikes','unavoidable','beyond','control'],
  'Governing Law':                 ['york','delaware','california','texas','england','ontario','florida','canada','republic','colorado','wales','illinois','pennsylvania','israel','massachusetts','ohio','nevada','virginia','jurisdiction'],
  'Indemnification':               ['indemnify','indemnified','harmless','losses','liabilities','damages','expenses','alleged','omission','prospectus','underwriter','statement','preliminary','defending','investigating'],
  'Insurance':                     ['insurance','coverage','insured','policy','policies','maintain','certificate','insurer','insurers','coverages','million','dollars','liability','workers','injury','comprehensive'],
  'IP Ownership Assignment':       ['assign','title','works','hire','assigns','assignments','copyright','patent','domain','registrations','innovations','transfers','execute','interest','property','intellectual'],
  'Irrevocable Or Perpetual License': ['perpetual','irrevocable','worldwide','royalty','free','invention','grants','intellectual','transferable','exploit','display','sublicenses','nonexclusive','import','improvement','reproduce','sublicensable'],
  'Joint IP Ownership':            ['jointly','joint','owned','undivided','inventions','prosecute','domain','patents','improvement','infringe','works','title','developed','patent','divisible'],
  'License Grant':                 ['grants','license','royalty','free','exclusive','worldwide','marks','solely','perpetual','sublicensable','reproduce','nonexclusive','display','irrevocable','revocable','grant','sublicense','transferable'],
  'Limited Liability':             ['damages','consequential','negligence','liability','tort','special','liable','punitive','incidental','arising','loss','exemplary','claim','lost','indirect','exceed','theory','profits'],
  'Liquidated Damages':            ['liquidated','damages','penalty','multiplied','estimate','forfeit','calculated','remaining','salary','monthly','termination'],
  'Minimum Commitment':            ['minimum','forecast','rolling','quarter','threshold','achieve','quantities','volume','subscribed','quantity','enrollment','annual','million'],
  'Most Favored Nation':           ['favorable','prices','lowest','charged','situated','favourable','pricing','similarly','discounted'],
  'Non-Compete':                   ['competitive','competing','competitor','compete','directly','indirectly','develop','sell','engage','commercialize','competitors'],
  'Non-Disparagement':             ['disparage','disparaging','disparages','reputation','disrepute','defame','negative','goodwill','injurious','comments'],
  'Non-Transferable License':      ['transferable','nontransferable','assignable','nonexclusive','sublicensable','sublicense','revocable','marks','trademarks','royalty'],
  'No-Solicit Of Customers':       ['solicit','divert','induce','entice','clients','customers','prospect','competitive','contact','directly','indirectly','discontinue'],
  'No-Solicit Of Employees':       ['solicit','employment','employee','employees','hire','employ','employed','encourage','entice','solicitation','solicitations','hiring'],
  'Notice Period To Terminate Renewal': ['renew','renewal','renewed','automatically','successive','periods','notifies','intention','expiry','automatic','gives','terminated','ninety','thirty','extension'],
  'Notice Requirements':           ['notice','notices','send','sent','delivery','receipt','certified','mail','email','address'],
  'Payment Terms':                 ['payment','invoice','invoices','royalties','royalty','compensation','fees','price','dollars','payable','paid','quarterly','monthly'],
  'Post-Termination Services':     ['transition','records','cooperate','orderly','possession','inventory','remaining','continue','expiration','terminated','return','transfer'],
  'Price Restrictions':            ['prices','price','increase','decrease','adjust','adjustment','rates','percent','exceed','discount','decreased','increases'],
  'Recording Consent Clause':      ['recording','recorded','record','video','audio','camera','cameras','consent','riders','passengers','passenger','surveillance','footage','dashcam','opt','ride'],
  'Renewal Term':                  ['renew','renewal','renewed','automatically','successive','periods','initial','least','automatic','extended','extend','additional','commence','expiry'],
  'Representations And Warranties':['represents','warrants','warrant','representation','accurate','true','correct','complete','material'],
  'Revenue/Profit Sharing':        ['revenue','revenues','royalty','percentage','percent','gross','royalties','calendar','shares','fiscal','generated','share','sold','commission','calculated'],
  'ROFR/ROFO/ROFN':                ['offer','refusal','option','negotiate','negotiation','abandon','bona','fide','first','assets','transaction','opportunity','patent'],
  'Source Code Escrow':            ['escrow','source','code','deposit','release','corrections','maintain','upgrades'],
  'Taxes':                         ['taxes','tax','taxable','taxation','withhold','withholding','vat','gst','excise','deduct','deduction','gross','income','sales','levy','levied','taxing','authority'],
  'Term':                          ['initial','commence','commencing','duration','continues','commencement'],
  'Termination For Convenience':   ['terminate','convenience','giving','ninety','thirty','sixty','reason','unilateral','terminated','advance','termination','least'],
  'Third Party Beneficiary':       ['beneficiary','beneficiaries','confer','intended','construed','benefit','enforce','protections','third','controlling'],
  'Unlimited License':             ['unlimited','utilization','perpetual','worldwide','grants','irrevocable','display','enterprise','viewings'],
  'Volume Restriction':            ['hours','appearances','exceed','quantity','quantities','slots','sessions','session','minutes','forecast'],
  'Warranty Duration':             ['warranty','defects','workmanship','warrants','defective','defect','latent','specifications','repaired','replaced','conform','conforming','acceptance','shipment'],
};

/** One-line hints fed to Groq to guide classification. */
export const CLAUSE_TYPE_HINTS: Record<string, string> = {
  'Affiliate License':               'sublicense rights granted to or from affiliates; sublicensee provisions',
  'AI Use Consent Clause':           'use of AI/automated decision-making/algorithmic or biometric analysis on rider or passenger data; consent or opt-in/opt-out for AI processing',
  'Anti-Assignment':                 'shall not assign, transfer, or delegate without consent; assignment prohibited',
  'Audit Rights':                    'right to audit books and records; inspection rights',
  'Background Check Requirement':    'driver/employee background checks, criminal history screening, MVR, fingerprinting, re-screening cadence (e.g. annual, biennial)',
  'Change Of Control':               'change of control, merger, acquisition, majority equity transfer',
  'Competitive Restriction Exception':'carve-out allowing otherwise prohibited competitive activity',
  'Confidentiality':                 'confidential information, proprietary information, non-disclosure obligation',
  'Consequential Damages Waiver':    'no consequential, special, indirect, or punitive damages; damages exclusion',
  'Covenant Not To Sue':             'covenant not to sue, release of claims, no legal action against',
  'Dispute Resolution':              'arbitration, mediation, dispute resolution, AAA, JAMS, governing jurisdiction',
  'Effective Date':                  'effective date, date this agreement becomes effective, commencement date',
  'Exclusivity':                     'exclusive right, exclusive license, exclusive territory; no other party',
  'Expiration Date':                 'expiration date, date this agreement expires, end date',
  'Force Majeure':                   'force majeure, act of God, circumstances beyond reasonable control',
  'Governing Law':                   'governed by laws of [state/country], choice of law, applicable law',
  'Indemnification':                 'indemnify, hold harmless, defend against third-party claims',
  'Insurance':                       'insurance, policy, coverage, carrier, certificate of insurance',
  'IP Ownership Assignment':         'assigns all right title and interest, work for hire, IP ownership',
  'Irrevocable Or Perpetual License':'irrevocable license, perpetual license, license that cannot be revoked',
  'Joint IP Ownership':              'jointly owned IP, co-ownership of intellectual property, joint inventions',
  'License Grant':                   'hereby grants a license; primary license grant to use/copy/distribute',
  'Limited Liability':               'limitation of liability, cap on liability, not exceed [amount], liable for no more than',
  'Liquidated Damages':              'liquidated damages, agreed damages, penalty for breach',
  'Minimum Commitment':              'minimum purchase, minimum commitment, at least N units/dollars per period',
  'Most Favored Nation':             'most favored nation, MFN, best pricing, no better terms to third parties',
  'Non-Compete':                     'shall not compete, non-compete, competitive activity restriction',
  'Non-Disparagement':               'shall not disparage, non-disparagement, no negative statements',
  'Non-Transferable License':        'non-transferable license, license may not be transferred or sublicensed',
  'No-Solicit Of Customers':         'shall not solicit customers or clients of the other party',
  'No-Solicit Of Employees':         'shall not solicit or hire employees of the other party',
  'Notice Period To Terminate Renewal':'notice required to prevent auto-renewal; days prior written notice to terminate',
  'Notice Requirements':            'notices under this agreement, written notice to, notice shall be given',
  'Parties':                         'this agreement is between [Party A] and [Party B]; identification of parties',
  'Payment Terms':                   'payment, fees, invoices, royalties, compensation, price, due within N days',
  'Post-Termination Services':       'obligations surviving termination, post-termination wind-down, transition services',
  'Price Restrictions':              'price restriction, price ceiling, price floor, price adjustment limits',
  'Recording Consent Clause':        'video/audio recording of rides, passenger or rider recording consent, dashcam/surveillance, opt-in or opt-out recording policy',
  'Renewal Term':                    'renewal term, shall automatically renew, successive [period] terms',
  'Representations And Warranties':  'represents and warrants, as of the date hereof, representations are true',
  'Revenue/Profit Sharing':          'revenue share, profit share, revenue split, percentage of revenues',
  'ROFR/ROFO/ROFN':                  'right of first refusal, right of first offer, ROFR, ROFO, ROFN',
  'Source Code Escrow':              'source code escrow, escrow agent, escrow deposit of source code',
  'Taxes':                           'taxes, tax obligations, withholding tax, VAT, GST, sales tax, tax responsibilities of parties',
  'Term':                            'term of this agreement, initial term, agreement shall continue for',
  'Termination For Convenience':     'may terminate for convenience, terminate without cause, terminate upon N days notice',
  'Third Party Beneficiary':         'third party beneficiary, intended beneficiary, rights of successors and assigns',
  'Unlimited License':               'unlimited license, unrestricted use, all-you-can-eat license',
  'Volume Restriction':              'volume restriction, quantity limit, maximum number of units',
  'Warranty Duration':               'warranty period, warranty term, warranty for N months/years',
};

import type { TopicLabel } from './legalUnitTypes';

const TYPE_TO_TOPIC: Partial<Record<string, TopicLabel[]>> = {
  'Confidentiality':              ['confidentiality'],
  'Data Protection Clause':       ['privacy', 'security'],
  'Insurance':                    ['insurance'],
  'Payment Terms':                ['payment'],
  'Audit Rights':                 ['audit'],
  'Audit Clause':                 ['audit'],
  'Background Check Requirement': ['background_check'],
  'Recording Consent Clause':     ['privacy'],
  'AI Use Consent Clause':        ['privacy'],
  'Indemnification':              ['indemnity'],
  'Limited Liability':            ['limitation_of_liability'],
  'Consequential Damages Waiver': ['limitation_of_liability'],
  'Term':                         ['term_termination'],
  'Termination For Convenience':  ['term_termination'],
  'Termination With Cause':       ['term_termination'],
  'Termination Without Cause':    ['term_termination'],
  'Renewal Term':                 ['term_termination'],
  'Notice Requirements':          ['notices'],
  'License Grant':                ['ip'],
  'Affiliate License':            ['ip'],
  'Irrevocable Or Perpetual License': ['ip'],
  'IP Ownership Assignment':      ['ip'],
  'Joint IP Ownership':           ['ip'],
  'Work for Hire / IP Ownership': ['ip'],
  'Anti-Assignment':              ['assignment'],
  'Assignment Clause':            ['assignment'],
  'Warranties':                   ['warranty'],
  'Warranty Duration':            ['warranty'],
  'Representations And Warranties': ['warranty'],
  'Compliance with Laws':         ['compliance_with_laws'],
  'Records Retention':            ['records_retention'],
};

export function mapCanonicalTypeToTopicLabels(clauseType: string): TopicLabel[] {
  return TYPE_TO_TOPIC[clauseType] ?? [];
}
