// ── Contract subtypes ────────────────────────────────────────────────────────
export const CONTRACT_SUBTYPE_OPTIONS = [
  { value: 'msa',                  label: 'MSA (Master Services Agreement)' },
  { value: 'nda',                  label: 'NDA (Non-Disclosure Agreement)' },
  { value: 'service_agreement',    label: 'Service Agreement' },
  { value: 'franchise_agreement',  label: 'Franchise Agreement' },
  { value: 'loan_agreement',       label: 'Loan Agreement' },
  { value: 'lease_agreement_sub',  label: 'Lease Agreement' },
  { value: 'master_lease',         label: 'Master Lease Agreement' },
  { value: 'general_contract',     label: 'General Contract' },
] as const;

export const CONTRACT_SUBTYPE_VALUES = CONTRACT_SUBTYPE_OPTIONS.map(o => o.value);
export type ContractSubtypeValue = typeof CONTRACT_SUBTYPE_OPTIONS[number]['value'];

// ── All document type options (for upload modal) ─────────────────────────────
export const DOCUMENT_TYPE_OPTIONS = [
  // Contract subtypes
  { value: 'msa',                  label: 'MSA — Master Services Agreement',    group: 'contract' },
  { value: 'nda',                  label: 'NDA — Non-Disclosure Agreement',     group: 'contract' },
  { value: 'service_agreement',    label: 'Service Agreement',                  group: 'contract' },
  { value: 'franchise_agreement',  label: 'Franchise Agreement',               group: 'contract' },
  { value: 'loan_agreement',       label: 'Loan Agreement',                     group: 'contract' },
  { value: 'master_lease',         label: 'Master Lease Agreement',             group: 'contract' },
  { value: 'general_contract',     label: 'General Contract',                   group: 'contract' },
  // Other document types
  { value: 'insurance_policy',     label: 'Insurance Policy',                   group: 'other' },
  { value: 'certificate_of_insurance', label: 'Certificate of Insurance (COI)', group: 'other' },
  { value: 'management_agreement', label: 'Management / Franchise Agreement',   group: 'other' },
  { value: 'loan_covenant',        label: 'Loan / Debt Covenant',              group: 'other' },
  { value: 'operating_permit',     label: 'Operating Permit / License',         group: 'other' },
  { value: 'lease_agreement',      label: 'Lease Agreement',                    group: 'other' },
  { value: 'general_review',       label: 'General Review (no profile)',        group: 'other' },
] as const;

export type DocumentTypeValue = typeof DOCUMENT_TYPE_OPTIONS[number]['value'];

// ── Full contract type categories (shared with upload modal) ─────────────────
export const CONTRACT_TYPE_CATEGORIES: { label: string; options: [string, string][] }[] = [
  { label: 'Employment & Labor', options: [
    ['employment_agreement',            'Employment Agreement'],
    ['executive_employment_agreement',  'Executive Employment Agreement'],
    ['employee_nda',                    'Non-Disclosure Agreement (Employee NDA)'],
    ['non_compete_agreement',           'Non-Compete Agreement'],
    ['non_solicitation_agreement',      'Non-Solicitation Agreement'],
    ['separation_agreement',            'Separation Agreement'],
    ['severance_agreement',             'Severance Agreement'],
    ['consulting_agreement',            'Consulting Agreement'],
    ['independent_contractor_agreement','Independent Contractor Agreement'],
    ['staffing_agreement',              'Staffing Agreement'],
    ['collective_bargaining_agreement', 'Collective Bargaining Agreement'],
    ['offer_letter',                    'Offer Letter'],
    ['employee_handbook_policy',        'Employee Handbook Policy'],
    ['commission_agreement',            'Commission Agreement'],
    ['bonus_agreement',                 'Bonus Agreement'],
  ]},
  { label: 'Technology & Software', options: [
    ['software_license_agreement',      'Software License Agreement'],
    ['saas_agreement',                  'SaaS Agreement'],
    ['software_development_agreement',  'Software Development Agreement'],
    ['technology_transfer_agreement',   'Technology Transfer Agreement'],
    ['source_code_license_agreement',   'Source Code License Agreement'],
    ['api_license_agreement',           'API License Agreement'],
    ['eula',                            'End User License Agreement (EULA)'],
    ['maintenance_support_agreement',   'Maintenance and Support Agreement'],
    ['system_integration_agreement',    'System Integration Agreement'],
    ['cloud_services_agreement',        'Cloud Services Agreement'],
    ['hosting_agreement',               'Hosting Agreement'],
    ['data_license_agreement',          'Data License Agreement'],
    ['open_source_license',             'Open Source License'],
  ]},
  { label: 'Intellectual Property', options: [
    ['patent_license_agreement',        'Patent License Agreement'],
    ['trademark_license_agreement',     'Trademark License Agreement'],
    ['copyright_license_agreement',     'Copyright License Agreement'],
    ['ip_assignment_agreement',         'IP Assignment Agreement'],
    ['co_development_agreement',        'Co-Development Agreement'],
    ['research_development_agreement',  'Research and Development Agreement'],
    ['joint_development_agreement',     'Joint Development Agreement'],
    ['trade_secret_agreement',          'Trade Secret Agreement'],
    ['franchise_agreement_ip',          'Franchise Agreement (IP-based)'],
    ['know_how_license',                'Know-How License'],
  ]},
  { label: 'Commercial & Sales', options: [
    ['msa',                             'Master Services Agreement (MSA)'],
    ['nda',                             'NDA — Non-Disclosure Agreement'],
    ['service_agreement',               'Service Agreement'],
    ['distribution_agreement',          'Distribution Agreement'],
    ['reseller_agreement',              'Reseller Agreement'],
    ['sales_agreement',                 'Sales Agreement'],
    ['purchase_order',                  'Purchase Order'],
    ['supply_agreement',                'Supply Agreement'],
    ['vendor_agreement',                'Service Provider Agreement'],
    ['marketing_agreement',             'Marketing Agreement'],
    ['advertising_agreement',           'Advertising Agreement'],
    ['sponsorship_agreement',           'Sponsorship Agreement'],
    ['co_marketing_agreement',          'Co-Marketing Agreement'],
    ['letter_of_intent',                'Letter of Intent (LOI)'],
    ['memorandum_of_understanding',     'Memorandum of Understanding (MOU)'],
    ['term_sheet',                      'Term Sheet'],
    ['general_contract',                'General Contract'],
  ]},
  { label: 'Real Estate & Property', options: [
    ['commercial_lease_agreement',      'Commercial Lease Agreement'],
    ['residential_lease_agreement',     'Residential Lease Agreement'],
    ['master_lease',                    'Master Lease Agreement'],
    ['lease_agreement',                 'Lease Agreement'],
    ['ground_lease',                    'Ground Lease'],
    ['sublease_agreement',              'Sublease Agreement'],
    ['lease_amendment',                 'Lease Amendment'],
    ['property_management_agreement',   'Property Management Agreement'],
    ['real_estate_purchase_agreement',  'Real Estate Purchase Agreement'],
    ['option_to_purchase',              'Option to Purchase'],
    ['easement_agreement',              'Easement Agreement'],
    ['right_of_way_agreement',          'Right of Way Agreement'],
    ['construction_loan_agreement',     'Construction Loan Agreement'],
    ['development_agreement',           'Development Agreement'],
  ]},
  { label: 'Finance & Lending', options: [
    ['loan_agreement',                  'Loan Agreement'],
    ['credit_agreement',                'Credit Agreement'],
    ['promissory_note',                 'Promissory Note'],
    ['security_agreement',              'Security Agreement'],
    ['pledge_agreement',                'Pledge Agreement'],
    ['guarantee_agreement',             'Guarantee Agreement'],
    ['line_of_credit_agreement',        'Line of Credit Agreement'],
    ['syndicated_loan_agreement',       'Syndicated Loan Agreement'],
    ['bridge_loan_agreement',           'Bridge Loan Agreement'],
    ['mezzanine_financing_agreement',   'Mezzanine Financing Agreement'],
    ['bond_indenture',                  'Bond Indenture'],
    ['debt_restructuring_agreement',    'Debt Restructuring Agreement'],
    ['loan_covenant',                   'Loan / Debt Covenant'],
  ]},
  { label: 'Corporate & M&A', options: [
    ['merger_agreement',                'Merger Agreement'],
    ['acquisition_agreement',           'Acquisition Agreement'],
    ['stock_purchase_agreement',        'Stock Purchase Agreement'],
    ['asset_purchase_agreement',        'Asset Purchase Agreement'],
    ['share_exchange_agreement',        'Share Exchange Agreement'],
    ['business_combination_agreement',  'Business Combination Agreement'],
    ['letter_of_intent_ma',             'Letter of Intent (M&A)'],
    ['ma_nda',                          'Confidentiality Agreement (M&A NDA)'],
    ['transition_services_agreement',   'Transition Services Agreement'],
    ['escrow_agreement',                'Escrow Agreement'],
  ]},
  { label: 'Investment & Venture', options: [
    ['venture_capital_agreement',       'Venture Capital Agreement'],
    ['term_sheet_vc',                   'Term Sheet (VC)'],
    ['shareholders_agreement',          'Shareholders Agreement'],
    ['investor_rights_agreement',       'Investor Rights Agreement'],
    ['subscription_agreement',          'Subscription Agreement'],
    ['convertible_note_agreement',      'Convertible Note Agreement'],
    ['safe_agreement',                  'SAFE Agreement'],
    ['co_investment_agreement',         'Co-Investment Agreement'],
    ['lp_agreement',                    'LP Agreement (Limited Partnership)'],
    ['gp_agreement',                    'GP Agreement (General Partnership)'],
    ['fund_formation_documents',        'Fund Formation Documents'],
  ]},
  { label: 'Professional Services', options: [
    ['advisory_agreement',              'Advisory Agreement'],
    ['management_consulting_agreement', 'Management Consulting Agreement'],
    ['management_agreement',            'Management Agreement'],
    ['legal_services_agreement',        'Legal Services Agreement'],
    ['accounting_services_agreement',   'Accounting Services Agreement'],
    ['engineering_services_agreement',  'Engineering Services Agreement'],
    ['architecture_agreement',          'Architecture Agreement'],
    ['it_services_agreement',           'IT Services Agreement'],
    ['marketing_services_agreement',    'Marketing Services Agreement'],
    ['event_management_agreement',      'Event Management Agreement'],
    ['translation_agreement',           'Translation Agreement'],
    ['research_agreement',              'Research Agreement'],
  ]},
  { label: 'Healthcare & Life Sciences', options: [
    ['clinical_trial_agreement',        'Clinical Trial Agreement'],
    ['research_collaboration_agreement','Research Collaboration Agreement'],
    ['pharma_license_agreement',        'License Agreement (Pharma)'],
    ['regulatory_compliance_agreement', 'Regulatory Compliance Agreement'],
    ['medical_device_agreement',        'Medical Device Agreement'],
    ['healthcare_services_agreement',   'Healthcare Services Agreement'],
    ['patient_services_agreement',      'Patient Services Agreement'],
    ['hipaa_baa',                       'HIPAA Business Associate Agreement'],
    ['pharmacy_agreement',              'Pharmacy Agreement'],
    ['lab_services_agreement',          'Lab Services Agreement'],
  ]},
  { label: 'Construction & Engineering', options: [
    ['construction_contract',           'Construction Contract'],
    ['epc_contract',                    'EPC Contract (Engineering Procurement Construction)'],
    ['design_build_agreement',          'Design-Build Agreement'],
    ['subcontractor_agreement',         'Subcontractor Agreement'],
    ['prime_contractor_agreement',      'Prime Contractor Agreement'],
    ['owner_contractor_agreement',      'Owner-Contractor Agreement'],
    ['lump_sum_contract',               'Lump Sum Contract'],
    ['cost_plus_contract',              'Cost-Plus Contract'],
    ['time_materials_contract',         'Time and Materials Contract'],
    ['project_management_agreement',    'Project Management Agreement'],
  ]},
  { label: 'Government & Public Sector', options: [
    ['government_contract',             'Government Contract'],
    ['far_contract',                    'FAR Contract (Federal Acquisition Regulation)'],
    ['defense_contract',                'Defense Contract'],
    ['grant_agreement',                 'Grant Agreement'],
    ['cooperative_agreement',           'Cooperative Agreement'],
    ['intergovernmental_agreement',     'Intergovernmental Agreement'],
    ['public_private_partnership',      'Public-Private Partnership Agreement'],
    ['municipal_contract',              'Municipal Contract'],
    ['procurement_contract',            'Procurement Contract'],
    ['operating_permit',                'Operating Permit'],
  ]},
  { label: 'Media & Entertainment', options: [
    ['talent_agreement',                'Talent Agreement'],
    ['production_agreement',            'Production Agreement'],
    ['media_distribution_agreement',    'Distribution Agreement (Media)'],
    ['media_license_agreement',         'Licensing Agreement (Media)'],
    ['co_production_agreement',         'Co-Production Agreement'],
    ['music_license_agreement',         'Music License Agreement'],
    ['synchronization_license',         'Synchronization License'],
    ['performance_agreement',           'Performance Agreement'],
    ['publishing_agreement',            'Publishing Agreement'],
    ['option_agreement_film',           'Option Agreement (Film/TV)'],
  ]},
  { label: 'Insurance', options: [
    ['insurance_policy',                'Insurance Policy'],
    ['certificate_of_insurance',        'Certificate of Insurance (COI)'],
    ['reinsurance_agreement',           'Reinsurance Agreement'],
    ['captive_insurance_agreement',     'Captive Insurance Agreement'],
    ['risk_sharing_agreement',          'Risk Sharing Agreement'],
    ['indemnification_agreement_ins',   'Indemnification Agreement (Insurance)'],
  ]},
  { label: 'International & Trade', options: [
    ['international_distribution_agreement', 'International Distribution Agreement'],
    ['export_agreement',                'Export Agreement'],
    ['import_agreement',                'Import Agreement'],
    ['trade_agreement',                 'Trade Agreement'],
    ['international_joint_venture',     'Joint Venture Agreement (International)'],
    ['cross_border_license_agreement',  'Cross-Border License Agreement'],
    ['international_employment_agreement', 'International Employment Agreement'],
    ['offshore_services_agreement',     'Offshore Services Agreement'],
  ]},
  { label: 'Data & Privacy', options: [
    ['data_processing_agreement',       'Data Processing Agreement (DPA)'],
    ['data_sharing_agreement',          'Data Sharing Agreement'],
    ['privacy_agreement',               'Privacy Agreement'],
    ['gdpr_dpa',                        'GDPR Data Processing Agreement'],
    ['ccpa_compliance_agreement',       'CCPA Compliance Agreement'],
    ['data_licensing_agreement',        'Data Licensing Agreement'],
    ['information_security_agreement',  'Information Security Agreement'],
    ['cybersecurity_agreement',         'Cybersecurity Agreement'],
  ]},
  { label: 'Settlement & Dispute Resolution', options: [
    ['settlement_agreement',            'Settlement Agreement'],
    ['mediation_agreement',             'Mediation Agreement'],
    ['arbitration_agreement',           'Arbitration Agreement'],
    ['consent_decree',                  'Consent Decree'],
    ['release_agreement',               'Release Agreement'],
    ['confidential_settlement_agreement','Confidential Settlement Agreement'],
    ['class_action_settlement',         'Class Action Settlement Agreement'],
  ]},
  { label: 'Nonprofit & Education', options: [
    ['nonprofit_grant_agreement',       'Grant Agreement (Nonprofit)'],
    ['donation_agreement',              'Donation Agreement'],
    ['nonprofit_sponsorship_agreement', 'Sponsorship Agreement (Nonprofit)'],
    ['academic_partnership_agreement',  'Academic Partnership Agreement'],
    ['academic_research_agreement',     'Research Agreement (Academic)'],
    ['student_services_agreement',      'Student Services Agreement'],
    ['affiliation_agreement',           'Affiliation Agreement'],
  ]},
  { label: 'Agriculture & Natural Resources', options: [
    ['agricultural_lease_agreement',    'Agricultural Lease Agreement'],
    ['crop_share_agreement',            'Crop Share Agreement'],
    ['water_rights_agreement',          'Water Rights Agreement'],
    ['mining_agreement',                'Mining Agreement'],
    ['timber_agreement',                'Timber Agreement'],
    ['oil_gas_lease',                   'Oil and Gas Lease'],
    ['grazing_agreement',               'Grazing Agreement'],
    ['conservation_easement',           'Conservation Easement'],
  ]},
  { label: 'Hospitality', options: [
    ['hotel_management_agreement',      'Hotel Management Agreement'],
    ['franchise_agreement_hospitality', 'Franchise Agreement (Hospitality)'],
    ['food_beverage_agreement',         'Food and Beverage Agreement'],
    ['event_services_agreement',        'Event Services Agreement'],
    ['catering_agreement',              'Catering Agreement'],
    ['tourism_agreement',               'Tourism Agreement'],
    ['accommodation_agreement',         'Accommodation Agreement'],
  ]},
  { label: 'Transportation & Logistics', options: [
    ['transportation_contract',         'Transportation Contract'],
    ['freight_agreement',               'Freight Agreement'],
    ['logistics_services_agreement',    'Logistics Services Agreement'],
    ['carrier_agreement',               'Carrier Agreement'],
    ['trucking_agreement',              'Trucking Agreement'],
    ['fleet_management_agreement',      'Fleet Management Agreement'],
    ['shipping_agreement',              'Shipping Agreement'],
    ['warehouse_agreement',             'Warehouse Agreement'],
    ['last_mile_delivery_agreement',    'Last-Mile Delivery Agreement'],
  ]},
  { label: 'Industrial & Field Services', options: [
    ['industrial_field_services_agreement', 'Industrial Field Services Agreement'],
    ['field_services_agreement',        'Field Services Agreement'],
    ['equipment_rental_agreement',      'Equipment Rental Agreement'],
    ['maintenance_services_agreement',  'Maintenance Services Agreement'],
    ['inspection_services_agreement',   'Inspection Services Agreement'],
    ['repair_services_agreement',       'Repair Services Agreement'],
    ['facilities_management_agreement', 'Facilities Management Agreement'],
    ['industrial_supply_agreement',     'Industrial Supply Agreement'],
    ['operations_maintenance_agreement','Operations & Maintenance Agreement'],
  ]},
  // Generic/ancillary types needed by automatic document-type classification
  // (bulk upload) that didn't already have a slot above — e.g. an amendment
  // or order form isn't its own "kind of agreement" so much as a modifier of
  // one, but still needs to be a selectable/classifiable type in its own right.
  { label: 'Ancillary & Transactional Documents', options: [
    ['statement_of_work',               'Statement of Work (SOW)'],
    ['order_form',                      'Order Form'],
    ['amendment',                       'Amendment'],
    ['addendum',                        'Addendum'],
    ['license_agreement',               'License Agreement'],
    ['partnership_agreement',           'Partnership Agreement'],
    ['professional_services_agreement', 'Professional Services Agreement'],
    ['supplier_agreement',              'Supplier Agreement'],
    ['transportation_services_agreement', 'Transportation Services Agreement'],
  ]},
  // Not bilateral agreements — a regulation binds no counterparty, and a
  // fact document (financial statement, registration, license, EIN/W-9)
  // states facts about one entity rather than obligations between two.
  // See lib/documents/classifyDocument.ts's NON_BILATERAL_DOCUMENT_TYPES,
  // which skips the paper-source/counterparty/relationship-role questions
  // entirely for these two — asking them of a state statute or a
  // certificate of good standing has nothing to answer.
  { label: 'Regulatory & Entity-Fact Documents', options: [
    ['regulation',              'Regulation / Legal Authority'],
    ['entity_fact_document',    'Entity Fact Document (financial statement, registration, license, certificate)'],
  ]},
  { label: 'Uncategorized', options: [
    ['unknown',                         'Unknown'],
  ]},
];

export const CONTRACT_TYPE_OPTIONS: { value: string; label: string; group: string }[] =
  CONTRACT_TYPE_CATEGORIES.flatMap(cat =>
    cat.options.map(([v, l]) => ({ value: v, label: l, group: cat.label }))
  );

export const CLAUSE_TO_OBLIGATION_TYPE: Record<string, string> = {
  insurer_notice:      'insurer_notice',
  claim_deadline:      'insurance_renewal',
  payment_date:        'covenant_compliance',
  premium_payment:     'insurance_renewal',
  financial_covenant:  'covenant_compliance',
  cross_default:       'lender_notice',
  renewal_deadline:    'permit_renewal',
  renewal_option:      'permit_renewal',
  reporting_duty:      'regulatory_filing',
  default_cure:        'lender_notice',
  revocation_trigger:  'regulatory_filing',
  termination:         'counterparty_notice',
  cancellation:        'insurance_renewal',
  indemnity:           'counterparty_notice',
  notice:              'counterparty_notice',
  guarantee:           'lender_notice',
};
